/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "aster_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace aster { namespace rpc {

int _kDistanceMetricValues[] = {
  DistanceMetric::L2,
  DistanceMetric::DOT,
  DistanceMetric::COSINE
};
const char* _kDistanceMetricNames[] = {
  "L2",
  "DOT",
  "COSINE"
};
const std::map<int, const char*> _DistanceMetric_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kDistanceMetricValues, _kDistanceMetricNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const DistanceMetric::type& val) {
  std::map<int, const char*>::const_iterator it = _DistanceMetric_VALUES_TO_NAMES.find(val);
  if (it != _DistanceMetric_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const DistanceMetric::type& val) {
  std::map<int, const char*>::const_iterator it = _DistanceMetric_VALUES_TO_NAMES.find(val);
  if (it != _DistanceMetric_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kConsistencyLevelValues[] = {
  ConsistencyLevel::ONE,
  ConsistencyLevel::LOCAL_ONE,
  ConsistencyLevel::QUORUM,
  ConsistencyLevel::ALL
};
const char* _kConsistencyLevelNames[] = {
  "ONE",
  "LOCAL_ONE",
  "QUORUM",
  "ALL"
};
const std::map<int, const char*> _ConsistencyLevel_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kConsistencyLevelValues, _kConsistencyLevelNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const ConsistencyLevel::type& val) {
  std::map<int, const char*>::const_iterator it = _ConsistencyLevel_VALUES_TO_NAMES.find(val);
  if (it != _ConsistencyLevel_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ConsistencyLevel::type& val) {
  std::map<int, const char*>::const_iterator it = _ConsistencyLevel_VALUES_TO_NAMES.find(val);
  if (it != _ConsistencyLevel_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kStorageModeValues[] = {
  StorageMode::HOT,
  StorageMode::WARM,
  StorageMode::COLD
};
const char* _kStorageModeNames[] = {
  "HOT",
  "WARM",
  "COLD"
};
const std::map<int, const char*> _StorageMode_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kStorageModeValues, _kStorageModeNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const StorageMode::type& val) {
  std::map<int, const char*>::const_iterator it = _StorageMode_VALUES_TO_NAMES.find(val);
  if (it != _StorageMode_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const StorageMode::type& val) {
  std::map<int, const char*>::const_iterator it = _StorageMode_VALUES_TO_NAMES.find(val);
  if (it != _StorageMode_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kIsolationLevelValues[] = {
  IsolationLevel::SHARED,
  IsolationLevel::DEDICATED
};
const char* _kIsolationLevelNames[] = {
  "SHARED",
  "DEDICATED"
};
const std::map<int, const char*> _IsolationLevel_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _kIsolationLevelValues, _kIsolationLevelNames), ::apache::thrift::TEnumIterator(-1, nullptr, nullptr));

std::ostream& operator<<(std::ostream& out, const IsolationLevel::type& val) {
  std::map<int, const char*>::const_iterator it = _IsolationLevel_VALUES_TO_NAMES.find(val);
  if (it != _IsolationLevel_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const IsolationLevel::type& val) {
  std::map<int, const char*>::const_iterator it = _IsolationLevel_VALUES_TO_NAMES.find(val);
  if (it != _IsolationLevel_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


VectorConfig::~VectorConfig() noexcept {
}

VectorConfig::VectorConfig() noexcept
   : dimension(0),
     metric(static_cast<DistanceMetric::type>(0)) {
}

void VectorConfig::__set_dimension(const int32_t val) {
  this->dimension = val;
}

void VectorConfig::__set_metric(const DistanceMetric::type val) {
  this->metric = val;
}
std::ostream& operator<<(std::ostream& out, const VectorConfig& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t VectorConfig::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_dimension = false;
  bool isset_metric = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->dimension);
          isset_dimension = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->metric = static_cast<DistanceMetric::type>(ecast0);
          isset_metric = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_dimension)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_metric)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t VectorConfig::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("VectorConfig");

  xfer += oprot->writeFieldBegin("dimension", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->dimension);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("metric", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(static_cast<int32_t>(this->metric));
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(VectorConfig &a, VectorConfig &b) noexcept {
  using ::std::swap;
  swap(a.dimension, b.dimension);
  swap(a.metric, b.metric);
}

bool VectorConfig::operator==(const VectorConfig & rhs) const
{
  if (!(dimension == rhs.dimension))
    return false;
  if (!(metric == rhs.metric))
    return false;
  return true;
}

VectorConfig::VectorConfig(const VectorConfig& other1) noexcept {
  dimension = other1.dimension;
  metric = other1.metric;
}
VectorConfig& VectorConfig::operator=(const VectorConfig& other2) noexcept {
  dimension = other2.dimension;
  metric = other2.metric;
  return *this;
}
void VectorConfig::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "VectorConfig(";
  out << "dimension=" << to_string(dimension);
  out << ", " << "metric=" << to_string(metric);
  out << ")";
}


HnswConfig::~HnswConfig() noexcept {
}

HnswConfig::HnswConfig() noexcept
   : m(16),
     efConstruction(128),
     efSearchDefault(64) {
}

void HnswConfig::__set_m(const int32_t val) {
  this->m = val;
__isset.m = true;
}

void HnswConfig::__set_efConstruction(const int32_t val) {
  this->efConstruction = val;
__isset.efConstruction = true;
}

void HnswConfig::__set_efSearchDefault(const int32_t val) {
  this->efSearchDefault = val;
__isset.efSearchDefault = true;
}
std::ostream& operator<<(std::ostream& out, const HnswConfig& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t HnswConfig::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->m);
          this->__isset.m = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->efConstruction);
          this->__isset.efConstruction = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->efSearchDefault);
          this->__isset.efSearchDefault = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t HnswConfig::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("HnswConfig");

  if (this->__isset.m) {
    xfer += oprot->writeFieldBegin("m", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32(this->m);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.efConstruction) {
    xfer += oprot->writeFieldBegin("efConstruction", ::apache::thrift::protocol::T_I32, 2);
    xfer += oprot->writeI32(this->efConstruction);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.efSearchDefault) {
    xfer += oprot->writeFieldBegin("efSearchDefault", ::apache::thrift::protocol::T_I32, 3);
    xfer += oprot->writeI32(this->efSearchDefault);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(HnswConfig &a, HnswConfig &b) noexcept {
  using ::std::swap;
  swap(a.m, b.m);
  swap(a.efConstruction, b.efConstruction);
  swap(a.efSearchDefault, b.efSearchDefault);
  swap(a.__isset, b.__isset);
}

bool HnswConfig::operator==(const HnswConfig & rhs) const
{
  if (__isset.m != rhs.__isset.m)
    return false;
  else if (__isset.m && !(m == rhs.m))
    return false;
  if (__isset.efConstruction != rhs.__isset.efConstruction)
    return false;
  else if (__isset.efConstruction && !(efConstruction == rhs.efConstruction))
    return false;
  if (__isset.efSearchDefault != rhs.__isset.efSearchDefault)
    return false;
  else if (__isset.efSearchDefault && !(efSearchDefault == rhs.efSearchDefault))
    return false;
  return true;
}

HnswConfig::HnswConfig(const HnswConfig& other3) noexcept {
  m = other3.m;
  efConstruction = other3.efConstruction;
  efSearchDefault = other3.efSearchDefault;
  __isset = other3.__isset;
}
HnswConfig& HnswConfig::operator=(const HnswConfig& other4) noexcept {
  m = other4.m;
  efConstruction = other4.efConstruction;
  efSearchDefault = other4.efSearchDefault;
  __isset = other4.__isset;
  return *this;
}
void HnswConfig::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "HnswConfig(";
  out << "m="; (__isset.m ? (out << to_string(m)) : (out << "<null>"));
  out << ", " << "efConstruction="; (__isset.efConstruction ? (out << to_string(efConstruction)) : (out << "<null>"));
  out << ", " << "efSearchDefault="; (__isset.efSearchDefault ? (out << to_string(efSearchDefault)) : (out << "<null>"));
  out << ")";
}


ResourceLimits::~ResourceLimits() noexcept {
}

ResourceLimits::ResourceLimits() noexcept
   : maxVectors(0LL),
     memoryBudgetBytes(0LL),
     maxQps(0),
     storageQuotaBytes(0LL),
     isolation(static_cast<IsolationLevel::type>(0)) {
}

void ResourceLimits::__set_maxVectors(const int64_t val) {
  this->maxVectors = val;
__isset.maxVectors = true;
}

void ResourceLimits::__set_memoryBudgetBytes(const int64_t val) {
  this->memoryBudgetBytes = val;
__isset.memoryBudgetBytes = true;
}

void ResourceLimits::__set_maxQps(const int32_t val) {
  this->maxQps = val;
__isset.maxQps = true;
}

void ResourceLimits::__set_storageQuotaBytes(const int64_t val) {
  this->storageQuotaBytes = val;
__isset.storageQuotaBytes = true;
}

void ResourceLimits::__set_isolation(const IsolationLevel::type val) {
  this->isolation = val;
__isset.isolation = true;
}
std::ostream& operator<<(std::ostream& out, const ResourceLimits& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ResourceLimits::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->maxVectors);
          this->__isset.maxVectors = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->memoryBudgetBytes);
          this->__isset.memoryBudgetBytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->maxQps);
          this->__isset.maxQps = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->storageQuotaBytes);
          this->__isset.storageQuotaBytes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast5;
          xfer += iprot->readI32(ecast5);
          this->isolation = static_cast<IsolationLevel::type>(ecast5);
          this->__isset.isolation = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t ResourceLimits::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ResourceLimits");

  if (this->__isset.maxVectors) {
    xfer += oprot->writeFieldBegin("maxVectors", ::apache::thrift::protocol::T_I64, 1);
    xfer += oprot->writeI64(this->maxVectors);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.memoryBudgetBytes) {
    xfer += oprot->writeFieldBegin("memoryBudgetBytes", ::apache::thrift::protocol::T_I64, 2);
    xfer += oprot->writeI64(this->memoryBudgetBytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.maxQps) {
    xfer += oprot->writeFieldBegin("maxQps", ::apache::thrift::protocol::T_I32, 3);
    xfer += oprot->writeI32(this->maxQps);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.storageQuotaBytes) {
    xfer += oprot->writeFieldBegin("storageQuotaBytes", ::apache::thrift::protocol::T_I64, 4);
    xfer += oprot->writeI64(this->storageQuotaBytes);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.isolation) {
    xfer += oprot->writeFieldBegin("isolation", ::apache::thrift::protocol::T_I32, 5);
    xfer += oprot->writeI32(static_cast<int32_t>(this->isolation));
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ResourceLimits &a, ResourceLimits &b) noexcept {
  using ::std::swap;
  swap(a.maxVectors, b.maxVectors);
  swap(a.memoryBudgetBytes, b.memoryBudgetBytes);
  swap(a.maxQps, b.maxQps);
  swap(a.storageQuotaBytes, b.storageQuotaBytes);
  swap(a.isolation, b.isolation);
  swap(a.__isset, b.__isset);
}

bool ResourceLimits::operator==(const ResourceLimits & rhs) const
{
  if (__isset.maxVectors != rhs.__isset.maxVectors)
    return false;
  else if (__isset.maxVectors && !(maxVectors == rhs.maxVectors))
    return false;
  if (__isset.memoryBudgetBytes != rhs.__isset.memoryBudgetBytes)
    return false;
  else if (__isset.memoryBudgetBytes && !(memoryBudgetBytes == rhs.memoryBudgetBytes))
    return false;
  if (__isset.maxQps != rhs.__isset.maxQps)
    return false;
  else if (__isset.maxQps && !(maxQps == rhs.maxQps))
    return false;
  if (__isset.storageQuotaBytes != rhs.__isset.storageQuotaBytes)
    return false;
  else if (__isset.storageQuotaBytes && !(storageQuotaBytes == rhs.storageQuotaBytes))
    return false;
  if (__isset.isolation != rhs.__isset.isolation)
    return false;
  else if (__isset.isolation && !(isolation == rhs.isolation))
    return false;
  return true;
}

ResourceLimits::ResourceLimits(const ResourceLimits& other6) noexcept {
  maxVectors = other6.maxVectors;
  memoryBudgetBytes = other6.memoryBudgetBytes;
  maxQps = other6.maxQps;
  storageQuotaBytes = other6.storageQuotaBytes;
  isolation = other6.isolation;
  __isset = other6.__isset;
}
ResourceLimits& ResourceLimits::operator=(const ResourceLimits& other7) noexcept {
  maxVectors = other7.maxVectors;
  memoryBudgetBytes = other7.memoryBudgetBytes;
  maxQps = other7.maxQps;
  storageQuotaBytes = other7.storageQuotaBytes;
  isolation = other7.isolation;
  __isset = other7.__isset;
  return *this;
}
void ResourceLimits::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ResourceLimits(";
  out << "maxVectors="; (__isset.maxVectors ? (out << to_string(maxVectors)) : (out << "<null>"));
  out << ", " << "memoryBudgetBytes="; (__isset.memoryBudgetBytes ? (out << to_string(memoryBudgetBytes)) : (out << "<null>"));
  out << ", " << "maxQps="; (__isset.maxQps ? (out << to_string(maxQps)) : (out << "<null>"));
  out << ", " << "storageQuotaBytes="; (__isset.storageQuotaBytes ? (out << to_string(storageQuotaBytes)) : (out << "<null>"));
  out << ", " << "isolation="; (__isset.isolation ? (out << to_string(isolation)) : (out << "<null>"));
  out << ")";
}


CollectionConfig::~CollectionConfig() noexcept {
}

CollectionConfig::CollectionConfig() noexcept
   : name(),
     replicationFactor(1),
     storageMode(static_cast<StorageMode::type>(0)) {
}

void CollectionConfig::__set_name(const std::string& val) {
  this->name = val;
}

void CollectionConfig::__set_vector(const VectorConfig& val) {
  this->vector = val;
}

void CollectionConfig::__set_hnsw(const HnswConfig& val) {
  this->hnsw = val;
__isset.hnsw = true;
}

void CollectionConfig::__set_replicationFactor(const int32_t val) {
  this->replicationFactor = val;
__isset.replicationFactor = true;
}

void CollectionConfig::__set_storageMode(const StorageMode::type val) {
  this->storageMode = val;
__isset.storageMode = true;
}

void CollectionConfig::__set_resourceLimits(const ResourceLimits& val) {
  this->resourceLimits = val;
__isset.resourceLimits = true;
}
std::ostream& operator<<(std::ostream& out, const CollectionConfig& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t CollectionConfig::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_name = false;
  bool isset_vector = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          isset_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->vector.read(iprot);
          isset_vector = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->hnsw.read(iprot);
          this->__isset.hnsw = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->replicationFactor);
          this->__isset.replicationFactor = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast8;
          xfer += iprot->readI32(ecast8);
          this->storageMode = static_cast<StorageMode::type>(ecast8);
          this->__isset.storageMode = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->resourceLimits.read(iprot);
          this->__isset.resourceLimits = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_vector)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t CollectionConfig::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("CollectionConfig");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("vector", ::apache::thrift::protocol::T_STRUCT, 2);
  xfer += this->vector.write(oprot);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.hnsw) {
    xfer += oprot->writeFieldBegin("hnsw", ::apache::thrift::protocol::T_STRUCT, 3);
    xfer += this->hnsw.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.replicationFactor) {
    xfer += oprot->writeFieldBegin("replicationFactor", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32(this->replicationFactor);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.storageMode) {
    xfer += oprot->writeFieldBegin("storageMode", ::apache::thrift::protocol::T_I32, 5);
    xfer += oprot->writeI32(static_cast<int32_t>(this->storageMode));
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.resourceLimits) {
    xfer += oprot->writeFieldBegin("resourceLimits", ::apache::thrift::protocol::T_STRUCT, 6);
    xfer += this->resourceLimits.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CollectionConfig &a, CollectionConfig &b) noexcept {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.vector, b.vector);
  swap(a.hnsw, b.hnsw);
  swap(a.replicationFactor, b.replicationFactor);
  swap(a.storageMode, b.storageMode);
  swap(a.resourceLimits, b.resourceLimits);
  swap(a.__isset, b.__isset);
}

bool CollectionConfig::operator==(const CollectionConfig & rhs) const
{
  if (!(name == rhs.name))
    return false;
  if (!(vector == rhs.vector))
    return false;
  if (__isset.hnsw != rhs.__isset.hnsw)
    return false;
  else if (__isset.hnsw && !(hnsw == rhs.hnsw))
    return false;
  if (__isset.replicationFactor != rhs.__isset.replicationFactor)
    return false;
  else if (__isset.replicationFactor && !(replicationFactor == rhs.replicationFactor))
    return false;
  if (__isset.storageMode != rhs.__isset.storageMode)
    return false;
  else if (__isset.storageMode && !(storageMode == rhs.storageMode))
    return false;
  if (__isset.resourceLimits != rhs.__isset.resourceLimits)
    return false;
  else if (__isset.resourceLimits && !(resourceLimits == rhs.resourceLimits))
    return false;
  return true;
}

CollectionConfig::CollectionConfig(const CollectionConfig& other9) {
  name = other9.name;
  vector = other9.vector;
  hnsw = other9.hnsw;
  replicationFactor = other9.replicationFactor;
  storageMode = other9.storageMode;
  resourceLimits = other9.resourceLimits;
  __isset = other9.__isset;
}
CollectionConfig& CollectionConfig::operator=(const CollectionConfig& other10) {
  name = other10.name;
  vector = other10.vector;
  hnsw = other10.hnsw;
  replicationFactor = other10.replicationFactor;
  storageMode = other10.storageMode;
  resourceLimits = other10.resourceLimits;
  __isset = other10.__isset;
  return *this;
}
void CollectionConfig::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CollectionConfig(";
  out << "name=" << to_string(name);
  out << ", " << "vector=" << to_string(vector);
  out << ", " << "hnsw="; (__isset.hnsw ? (out << to_string(hnsw)) : (out << "<null>"));
  out << ", " << "replicationFactor="; (__isset.replicationFactor ? (out << to_string(replicationFactor)) : (out << "<null>"));
  out << ", " << "storageMode="; (__isset.storageMode ? (out << to_string(storageMode)) : (out << "<null>"));
  out << ", " << "resourceLimits="; (__isset.resourceLimits ? (out << to_string(resourceLimits)) : (out << "<null>"));
  out << ")";
}


Document::~Document() noexcept {
}

Document::Document() noexcept
   : id(),
     vector(),
     metadata(),
     timestampMicros(0) {
}

void Document::__set_id(const std::string& val) {
  this->id = val;
}

void Document::__set_vector(const std::string& val) {
  this->vector = val;
}

void Document::__set_metadata(const std::string& val) {
  this->metadata = val;
__isset.metadata = true;
}

void Document::__set_tags(const std::set<std::string> & val) {
  this->tags = val;
__isset.tags = true;
}

void Document::__set_timestampMicros(const int64_t val) {
  this->timestampMicros = val;
__isset.timestampMicros = true;
}
std::ostream& operator<<(std::ostream& out, const Document& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Document::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_id = false;
  bool isset_vector = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->id);
          isset_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->vector);
          isset_vector = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->metadata);
          this->__isset.metadata = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_SET) {
          {
            this->tags.clear();
            uint32_t _size11;
            ::apache::thrift::protocol::TType _etype14;
            xfer += iprot->readSetBegin(_etype14, _size11);
            uint32_t _i15;
            for (_i15 = 0; _i15 < _size11; ++_i15)
            {
              std::string _elem16;
              xfer += iprot->readString(_elem16);
              this->tags.insert(_elem16);
            }
            xfer += iprot->readSetEnd();
          }
          this->__isset.tags = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->timestampMicros);
          this->__isset.timestampMicros = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_vector)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Document::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Document");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("vector", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeBinary(this->vector);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.metadata) {
    xfer += oprot->writeFieldBegin("metadata", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeBinary(this->metadata);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.tags) {
    xfer += oprot->writeFieldBegin("tags", ::apache::thrift::protocol::T_SET, 4);
    {
      xfer += oprot->writeSetBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->tags.size()));
      std::set<std::string> ::const_iterator _iter17;
      for (_iter17 = this->tags.begin(); _iter17 != this->tags.end(); ++_iter17)
      {
        xfer += oprot->writeString((*_iter17));
      }
      xfer += oprot->writeSetEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.timestampMicros) {
    xfer += oprot->writeFieldBegin("timestampMicros", ::apache::thrift::protocol::T_I64, 5);
    xfer += oprot->writeI64(this->timestampMicros);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Document &a, Document &b) noexcept {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.vector, b.vector);
  swap(a.metadata, b.metadata);
  swap(a.tags, b.tags);
  swap(a.timestampMicros, b.timestampMicros);
  swap(a.__isset, b.__isset);
}

bool Document::operator==(const Document & rhs) const
{
  if (!(id == rhs.id))
    return false;
  if (!(vector == rhs.vector))
    return false;
  if (__isset.metadata != rhs.__isset.metadata)
    return false;
  else if (__isset.metadata && !(metadata == rhs.metadata))
    return false;
  if (__isset.tags != rhs.__isset.tags)
    return false;
  else if (__isset.tags && !(tags == rhs.tags))
    return false;
  if (__isset.timestampMicros != rhs.__isset.timestampMicros)
    return false;
  else if (__isset.timestampMicros && !(timestampMicros == rhs.timestampMicros))
    return false;
  return true;
}

Document::Document(const Document& other18) {
  id = other18.id;
  vector = other18.vector;
  metadata = other18.metadata;
  tags = other18.tags;
  timestampMicros = other18.timestampMicros;
  __isset = other18.__isset;
}
Document& Document::operator=(const Document& other19) {
  id = other19.id;
  vector = other19.vector;
  metadata = other19.metadata;
  tags = other19.tags;
  timestampMicros = other19.timestampMicros;
  __isset = other19.__isset;
  return *this;
}
void Document::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Document(";
  out << "id=" << to_string(id);
  out << ", " << "vector=" << to_string(vector);
  out << ", " << "metadata="; (__isset.metadata ? (out << to_string(metadata)) : (out << "<null>"));
  out << ", " << "tags="; (__isset.tags ? (out << to_string(tags)) : (out << "<null>"));
  out << ", " << "timestampMicros="; (__isset.timestampMicros ? (out << to_string(timestampMicros)) : (out << "<null>"));
  out << ")";
}


SearchRequest::~SearchRequest() noexcept {
}

SearchRequest::SearchRequest() noexcept
   : collection(),
     vector(),
     topK(10),
     efSearch(0),
     consistency(static_cast<ConsistencyLevel::type>(0)) {
}

void SearchRequest::__set_collection(const std::string& val) {
  this->collection = val;
}

void SearchRequest::__set_vector(const std::string& val) {
  this->vector = val;
}

void SearchRequest::__set_topK(const int32_t val) {
  this->topK = val;
__isset.topK = true;
}

void SearchRequest::__set_efSearch(const int32_t val) {
  this->efSearch = val;
__isset.efSearch = true;
}

void SearchRequest::__set_tags(const std::set<std::string> & val) {
  this->tags = val;
__isset.tags = true;
}

void SearchRequest::__set_consistency(const ConsistencyLevel::type val) {
  this->consistency = val;
__isset.consistency = true;
}
std::ostream& operator<<(std::ostream& out, const SearchRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SearchRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_collection = false;
  bool isset_vector = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->collection);
          isset_collection = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->vector);
          isset_vector = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->topK);
          this->__isset.topK = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->efSearch);
          this->__isset.efSearch = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_SET) {
          {
            this->tags.clear();
            uint32_t _size20;
            ::apache::thrift::protocol::TType _etype23;
            xfer += iprot->readSetBegin(_etype23, _size20);
            uint32_t _i24;
            for (_i24 = 0; _i24 < _size20; ++_i24)
            {
              std::string _elem25;
              xfer += iprot->readString(_elem25);
              this->tags.insert(_elem25);
            }
            xfer += iprot->readSetEnd();
          }
          this->__isset.tags = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast26;
          xfer += iprot->readI32(ecast26);
          this->consistency = static_cast<ConsistencyLevel::type>(ecast26);
          this->__isset.consistency = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_collection)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_vector)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t SearchRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SearchRequest");

  xfer += oprot->writeFieldBegin("collection", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->collection);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("vector", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeBinary(this->vector);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.topK) {
    xfer += oprot->writeFieldBegin("topK", ::apache::thrift::protocol::T_I32, 3);
    xfer += oprot->writeI32(this->topK);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.efSearch) {
    xfer += oprot->writeFieldBegin("efSearch", ::apache::thrift::protocol::T_I32, 4);
    xfer += oprot->writeI32(this->efSearch);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.tags) {
    xfer += oprot->writeFieldBegin("tags", ::apache::thrift::protocol::T_SET, 5);
    {
      xfer += oprot->writeSetBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->tags.size()));
      std::set<std::string> ::const_iterator _iter27;
      for (_iter27 = this->tags.begin(); _iter27 != this->tags.end(); ++_iter27)
      {
        xfer += oprot->writeString((*_iter27));
      }
      xfer += oprot->writeSetEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.consistency) {
    xfer += oprot->writeFieldBegin("consistency", ::apache::thrift::protocol::T_I32, 6);
    xfer += oprot->writeI32(static_cast<int32_t>(this->consistency));
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SearchRequest &a, SearchRequest &b) noexcept {
  using ::std::swap;
  swap(a.collection, b.collection);
  swap(a.vector, b.vector);
  swap(a.topK, b.topK);
  swap(a.efSearch, b.efSearch);
  swap(a.tags, b.tags);
  swap(a.consistency, b.consistency);
  swap(a.__isset, b.__isset);
}

bool SearchRequest::operator==(const SearchRequest & rhs) const
{
  if (!(collection == rhs.collection))
    return false;
  if (!(vector == rhs.vector))
    return false;
  if (__isset.topK != rhs.__isset.topK)
    return false;
  else if (__isset.topK && !(topK == rhs.topK))
    return false;
  if (__isset.efSearch != rhs.__isset.efSearch)
    return false;
  else if (__isset.efSearch && !(efSearch == rhs.efSearch))
    return false;
  if (__isset.tags != rhs.__isset.tags)
    return false;
  else if (__isset.tags && !(tags == rhs.tags))
    return false;
  if (__isset.consistency != rhs.__isset.consistency)
    return false;
  else if (__isset.consistency && !(consistency == rhs.consistency))
    return false;
  return true;
}

SearchRequest::SearchRequest(const SearchRequest& other28) {
  collection = other28.collection;
  vector = other28.vector;
  topK = other28.topK;
  efSearch = other28.efSearch;
  tags = other28.tags;
  consistency = other28.consistency;
  __isset = other28.__isset;
}
SearchRequest& SearchRequest::operator=(const SearchRequest& other29) {
  collection = other29.collection;
  vector = other29.vector;
  topK = other29.topK;
  efSearch = other29.efSearch;
  tags = other29.tags;
  consistency = other29.consistency;
  __isset = other29.__isset;
  return *this;
}
void SearchRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SearchRequest(";
  out << "collection=" << to_string(collection);
  out << ", " << "vector=" << to_string(vector);
  out << ", " << "topK="; (__isset.topK ? (out << to_string(topK)) : (out << "<null>"));
  out << ", " << "efSearch="; (__isset.efSearch ? (out << to_string(efSearch)) : (out << "<null>"));
  out << ", " << "tags="; (__isset.tags ? (out << to_string(tags)) : (out << "<null>"));
  out << ", " << "consistency="; (__isset.consistency ? (out << to_string(consistency)) : (out << "<null>"));
  out << ")";
}


SearchHit::~SearchHit() noexcept {
}

SearchHit::SearchHit() noexcept
   : id(),
     score(0),
     metadata() {
}

void SearchHit::__set_id(const std::string& val) {
  this->id = val;
}

void SearchHit::__set_score(const double val) {
  this->score = val;
}

void SearchHit::__set_metadata(const std::string& val) {
  this->metadata = val;
__isset.metadata = true;
}
std::ostream& operator<<(std::ostream& out, const SearchHit& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SearchHit::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_id = false;
  bool isset_score = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->id);
          isset_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->score);
          isset_score = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->metadata);
          this->__isset.metadata = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_score)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t SearchHit::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SearchHit");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("score", ::apache::thrift::protocol::T_DOUBLE, 2);
  xfer += oprot->writeDouble(this->score);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.metadata) {
    xfer += oprot->writeFieldBegin("metadata", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeBinary(this->metadata);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SearchHit &a, SearchHit &b) noexcept {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.score, b.score);
  swap(a.metadata, b.metadata);
  swap(a.__isset, b.__isset);
}

bool SearchHit::operator==(const SearchHit & rhs) const
{
  if (!(id == rhs.id))
    return false;
  if (!(score == rhs.score))
    return false;
  if (__isset.metadata != rhs.__isset.metadata)
    return false;
  else if (__isset.metadata && !(metadata == rhs.metadata))
    return false;
  return true;
}

SearchHit::SearchHit(const SearchHit& other30) {
  id = other30.id;
  score = other30.score;
  metadata = other30.metadata;
  __isset = other30.__isset;
}
SearchHit& SearchHit::operator=(const SearchHit& other31) {
  id = other31.id;
  score = other31.score;
  metadata = other31.metadata;
  __isset = other31.__isset;
  return *this;
}
void SearchHit::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SearchHit(";
  out << "id=" << to_string(id);
  out << ", " << "score=" << to_string(score);
  out << ", " << "metadata="; (__isset.metadata ? (out << to_string(metadata)) : (out << "<null>"));
  out << ")";
}


SearchResponse::~SearchResponse() noexcept {
}

SearchResponse::SearchResponse() noexcept {
}

void SearchResponse::__set_hits(const std::vector<SearchHit> & val) {
  this->hits = val;
}
std::ostream& operator<<(std::ostream& out, const SearchResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SearchResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_hits = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->hits.clear();
            uint32_t _size32;
            ::apache::thrift::protocol::TType _etype35;
            xfer += iprot->readListBegin(_etype35, _size32);
            this->hits.resize(_size32);
            uint32_t _i36;
            for (_i36 = 0; _i36 < _size32; ++_i36)
            {
              xfer += this->hits[_i36].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_hits = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_hits)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t SearchResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SearchResponse");

  xfer += oprot->writeFieldBegin("hits", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->hits.size()));
    std::vector<SearchHit> ::const_iterator _iter37;
    for (_iter37 = this->hits.begin(); _iter37 != this->hits.end(); ++_iter37)
    {
      xfer += (*_iter37).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SearchResponse &a, SearchResponse &b) noexcept {
  using ::std::swap;
  swap(a.hits, b.hits);
}

bool SearchResponse::operator==(const SearchResponse & rhs) const
{
  if (!(hits == rhs.hits))
    return false;
  return true;
}

SearchResponse::SearchResponse(const SearchResponse& other38) {
  hits = other38.hits;
}
SearchResponse& SearchResponse::operator=(const SearchResponse& other39) {
  hits = other39.hits;
  return *this;
}
void SearchResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SearchResponse(";
  out << "hits=" << to_string(hits);
  out << ")";
}


AsterError::~AsterError() noexcept {
}

AsterError::AsterError() noexcept
   : code(0),
     message() {
}

void AsterError::__set_code(const int32_t val) {
  this->code = val;
}

void AsterError::__set_message(const std::string& val) {
  this->message = val;
}
std::ostream& operator<<(std::ostream& out, const AsterError& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t AsterError::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_code = false;
  bool isset_message = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->code);
          isset_code = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->message);
          isset_message = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_code)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_message)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t AsterError::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("AsterError");

  xfer += oprot->writeFieldBegin("code", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->code);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("message", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->message);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(AsterError &a, AsterError &b) noexcept {
  using ::std::swap;
  swap(a.code, b.code);
  swap(a.message, b.message);
}

bool AsterError::operator==(const AsterError & rhs) const
{
  if (!(code == rhs.code))
    return false;
  if (!(message == rhs.message))
    return false;
  return true;
}

AsterError::AsterError(const AsterError& other40) : TException() {
  code = other40.code;
  message = other40.message;
}
AsterError& AsterError::operator=(const AsterError& other41) {
  code = other41.code;
  message = other41.message;
  return *this;
}
void AsterError::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "AsterError(";
  out << "code=" << to_string(code);
  out << ", " << "message=" << to_string(message);
  out << ")";
}

const char* AsterError::what() const noexcept {
  try {
    std::stringstream ss;
    ss << "TException - service has thrown: " << *this;
    this->thriftTExceptionMessageHolder_ = ss.str();
    return this->thriftTExceptionMessageHolder_.c_str();
  } catch (const std::exception&) {
    return "TException - service has thrown: AsterError";
  }
}

}} // namespace
