/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "aster_constants.h"

namespace aster { namespace rpc {

const asterConstants g_aster_constants;

asterConstants::asterConstants() {
  ASTER_IDL_MAJOR = 1;

}

}} // namespace

