/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aster_TYPES_H
#define aster_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace aster { namespace rpc {

struct DistanceMetric {
  enum type {
    L2 = 0,
    DOT = 1,
    COSINE = 2
  };
};

extern const std::map<int, const char*> _DistanceMetric_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const DistanceMetric::type& val);

std::string to_string(const DistanceMetric::type& val);

struct ConsistencyLevel {
  enum type {
    ONE = 0,
    LOCAL_ONE = 1,
    QUORUM = 2,
    ALL = 3
  };
};

extern const std::map<int, const char*> _ConsistencyLevel_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ConsistencyLevel::type& val);

std::string to_string(const ConsistencyLevel::type& val);

class VectorConfig;

class HnswConfig;

class CollectionConfig;

class Document;

class SearchRequest;

class SearchHit;

class SearchResponse;

class AsterError;


class VectorConfig : public virtual ::apache::thrift::TBase {
 public:

  VectorConfig(const VectorConfig&) noexcept;
  VectorConfig& operator=(const VectorConfig&) noexcept;
  VectorConfig() noexcept;

  virtual ~VectorConfig() noexcept;
  int32_t dimension;
  /**
   * 
   * @see DistanceMetric
   */
  DistanceMetric::type metric;

  void __set_dimension(const int32_t val);

  void __set_metric(const DistanceMetric::type val);

  bool operator == (const VectorConfig & rhs) const;
  bool operator != (const VectorConfig &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VectorConfig & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(VectorConfig &a, VectorConfig &b) noexcept;

std::ostream& operator<<(std::ostream& out, const VectorConfig& obj);

typedef struct _HnswConfig__isset {
  _HnswConfig__isset() : m(true), efConstruction(true), efSearchDefault(true) {}
  bool m :1;
  bool efConstruction :1;
  bool efSearchDefault :1;
} _HnswConfig__isset;

class HnswConfig : public virtual ::apache::thrift::TBase {
 public:

  HnswConfig(const HnswConfig&) noexcept;
  HnswConfig& operator=(const HnswConfig&) noexcept;
  HnswConfig() noexcept;

  virtual ~HnswConfig() noexcept;
  int32_t m;
  int32_t efConstruction;
  int32_t efSearchDefault;

  _HnswConfig__isset __isset;

  void __set_m(const int32_t val);

  void __set_efConstruction(const int32_t val);

  void __set_efSearchDefault(const int32_t val);

  bool operator == (const HnswConfig & rhs) const;
  bool operator != (const HnswConfig &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HnswConfig & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(HnswConfig &a, HnswConfig &b) noexcept;

std::ostream& operator<<(std::ostream& out, const HnswConfig& obj);

typedef struct _CollectionConfig__isset {
  _CollectionConfig__isset() : hnsw(false), replicationFactor(true) {}
  bool hnsw :1;
  bool replicationFactor :1;
} _CollectionConfig__isset;

class CollectionConfig : public virtual ::apache::thrift::TBase {
 public:

  CollectionConfig(const CollectionConfig&);
  CollectionConfig& operator=(const CollectionConfig&);
  CollectionConfig() noexcept;

  virtual ~CollectionConfig() noexcept;
  std::string name;
  VectorConfig vector;
  HnswConfig hnsw;
  int32_t replicationFactor;

  _CollectionConfig__isset __isset;

  void __set_name(const std::string& val);

  void __set_vector(const VectorConfig& val);

  void __set_hnsw(const HnswConfig& val);

  void __set_replicationFactor(const int32_t val);

  bool operator == (const CollectionConfig & rhs) const;
  bool operator != (const CollectionConfig &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CollectionConfig & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(CollectionConfig &a, CollectionConfig &b) noexcept;

std::ostream& operator<<(std::ostream& out, const CollectionConfig& obj);

typedef struct _Document__isset {
  _Document__isset() : metadata(false), tags(false), timestampMicros(false) {}
  bool metadata :1;
  bool tags :1;
  bool timestampMicros :1;
} _Document__isset;

class Document : public virtual ::apache::thrift::TBase {
 public:

  Document(const Document&);
  Document& operator=(const Document&);
  Document() noexcept;

  virtual ~Document() noexcept;
  std::string id;
  std::string vector;
  std::string metadata;
  std::set<std::string>  tags;
  int64_t timestampMicros;

  _Document__isset __isset;

  void __set_id(const std::string& val);

  void __set_vector(const std::string& val);

  void __set_metadata(const std::string& val);

  void __set_tags(const std::set<std::string> & val);

  void __set_timestampMicros(const int64_t val);

  bool operator == (const Document & rhs) const;
  bool operator != (const Document &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Document & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Document &a, Document &b) noexcept;

std::ostream& operator<<(std::ostream& out, const Document& obj);

typedef struct _SearchRequest__isset {
  _SearchRequest__isset() : topK(true), efSearch(false), tags(false), consistency(true) {}
  bool topK :1;
  bool efSearch :1;
  bool tags :1;
  bool consistency :1;
} _SearchRequest__isset;

class SearchRequest : public virtual ::apache::thrift::TBase {
 public:

  SearchRequest(const SearchRequest&);
  SearchRequest& operator=(const SearchRequest&);
  SearchRequest() noexcept;

  virtual ~SearchRequest() noexcept;
  std::string collection;
  std::string vector;
  int32_t topK;
  int32_t efSearch;
  std::set<std::string>  tags;
  /**
   * 
   * @see ConsistencyLevel
   */
  ConsistencyLevel::type consistency;

  _SearchRequest__isset __isset;

  void __set_collection(const std::string& val);

  void __set_vector(const std::string& val);

  void __set_topK(const int32_t val);

  void __set_efSearch(const int32_t val);

  void __set_tags(const std::set<std::string> & val);

  void __set_consistency(const ConsistencyLevel::type val);

  bool operator == (const SearchRequest & rhs) const;
  bool operator != (const SearchRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SearchRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SearchRequest &a, SearchRequest &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SearchRequest& obj);

typedef struct _SearchHit__isset {
  _SearchHit__isset() : metadata(false) {}
  bool metadata :1;
} _SearchHit__isset;

class SearchHit : public virtual ::apache::thrift::TBase {
 public:

  SearchHit(const SearchHit&);
  SearchHit& operator=(const SearchHit&);
  SearchHit() noexcept;

  virtual ~SearchHit() noexcept;
  std::string id;
  double score;
  std::string metadata;

  _SearchHit__isset __isset;

  void __set_id(const std::string& val);

  void __set_score(const double val);

  void __set_metadata(const std::string& val);

  bool operator == (const SearchHit & rhs) const;
  bool operator != (const SearchHit &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SearchHit & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SearchHit &a, SearchHit &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SearchHit& obj);


class SearchResponse : public virtual ::apache::thrift::TBase {
 public:

  SearchResponse(const SearchResponse&);
  SearchResponse& operator=(const SearchResponse&);
  SearchResponse() noexcept;

  virtual ~SearchResponse() noexcept;
  std::vector<SearchHit>  hits;

  void __set_hits(const std::vector<SearchHit> & val);

  bool operator == (const SearchResponse & rhs) const;
  bool operator != (const SearchResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SearchResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(SearchResponse &a, SearchResponse &b) noexcept;

std::ostream& operator<<(std::ostream& out, const SearchResponse& obj);


class AsterError : public ::apache::thrift::TException {
 public:

  AsterError(const AsterError&);
  AsterError& operator=(const AsterError&);
  AsterError() noexcept;

  virtual ~AsterError() noexcept;
  int32_t code;
  std::string message;

  void __set_code(const int32_t val);

  void __set_message(const std::string& val);

  bool operator == (const AsterError & rhs) const;
  bool operator != (const AsterError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AsterError & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const noexcept override;
};

void swap(AsterError &a, AsterError &b) noexcept;

std::ostream& operator<<(std::ostream& out, const AsterError& obj);

}} // namespace

#endif
