/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef aster_CONSTANTS_H
#define aster_CONSTANTS_H

#include "aster_types.h"

namespace aster { namespace rpc {

class asterConstants {
 public:
  asterConstants();

  int32_t ASTER_IDL_MAJOR;
};

extern const asterConstants g_aster_constants;

}} // namespace

#endif
