/**
 * Autogenerated by Thrift Compiler (0.24.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Aster_H
#define Aster_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "aster_types.h"

namespace aster { namespace rpc {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class AsterIf {
 public:
  virtual ~AsterIf() {}
  virtual void createCollection(const std::string& name) = 0;
  virtual void configureCollection(const CollectionConfig& config) = 0;
  virtual void dropCollection(const std::string& name) = 0;
  virtual void upsert(const std::string& collection, const Document& doc, const ConsistencyLevel::type consistency) = 0;
  virtual void get(Document& _return, const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) = 0;
  virtual void remove(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) = 0;
  virtual void search(SearchResponse& _return, const SearchRequest& req) = 0;
};

class AsterIfFactory {
 public:
  typedef AsterIf Handler;

  virtual ~AsterIfFactory() {}

  virtual AsterIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(AsterIf* /* handler */) = 0;
  };

class AsterIfSingletonFactory : virtual public AsterIfFactory {
 public:
  AsterIfSingletonFactory(const ::std::shared_ptr<AsterIf>& iface) : iface_(iface) {}
  virtual ~AsterIfSingletonFactory() {}

  virtual AsterIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(AsterIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<AsterIf> iface_;
};

class AsterNull : virtual public AsterIf {
 public:
  virtual ~AsterNull() {}
  void createCollection(const std::string& /* name */) override {
    return;
  }
  void configureCollection(const CollectionConfig& /* config */) override {
    return;
  }
  void dropCollection(const std::string& /* name */) override {
    return;
  }
  void upsert(const std::string& /* collection */, const Document& /* doc */, const ConsistencyLevel::type /* consistency */) override {
    return;
  }
  void get(Document& /* _return */, const std::string& /* collection */, const std::string& /* id */, const ConsistencyLevel::type /* consistency */) override {
    return;
  }
  void remove(const std::string& /* collection */, const std::string& /* id */, const ConsistencyLevel::type /* consistency */) override {
    return;
  }
  void search(SearchResponse& /* _return */, const SearchRequest& /* req */) override {
    return;
  }
};

typedef struct _Aster_createCollection_args__isset {
  _Aster_createCollection_args__isset() : name(false) {}
  bool name :1;
} _Aster_createCollection_args__isset;

class Aster_createCollection_args {
 public:

  Aster_createCollection_args(const Aster_createCollection_args&);
  Aster_createCollection_args& operator=(const Aster_createCollection_args&);
  Aster_createCollection_args() noexcept;

  virtual ~Aster_createCollection_args() noexcept;
  std::string name;

  _Aster_createCollection_args__isset __isset;

  void __set_name(const std::string& val);

  bool operator == (const Aster_createCollection_args & rhs) const;
  bool operator != (const Aster_createCollection_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_createCollection_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_createCollection_pargs {
 public:


  virtual ~Aster_createCollection_pargs() noexcept;
  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_createCollection_result__isset {
  _Aster_createCollection_result__isset() : e(false) {}
  bool e :1;
} _Aster_createCollection_result__isset;

class Aster_createCollection_result {
 public:

  Aster_createCollection_result(const Aster_createCollection_result&);
  Aster_createCollection_result& operator=(const Aster_createCollection_result&);
  Aster_createCollection_result() noexcept;

  virtual ~Aster_createCollection_result() noexcept;
  AsterError e;

  _Aster_createCollection_result__isset __isset;

  void __set_e(const AsterError& val);

  bool operator == (const Aster_createCollection_result & rhs) const;
  bool operator != (const Aster_createCollection_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_createCollection_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_createCollection_presult__isset {
  _Aster_createCollection_presult__isset() : e(false) {}
  bool e :1;
} _Aster_createCollection_presult__isset;

class Aster_createCollection_presult {
 public:


  virtual ~Aster_createCollection_presult() noexcept;
  AsterError e;

  _Aster_createCollection_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Aster_configureCollection_args__isset {
  _Aster_configureCollection_args__isset() : config(false) {}
  bool config :1;
} _Aster_configureCollection_args__isset;

class Aster_configureCollection_args {
 public:

  Aster_configureCollection_args(const Aster_configureCollection_args&);
  Aster_configureCollection_args& operator=(const Aster_configureCollection_args&);
  Aster_configureCollection_args() noexcept;

  virtual ~Aster_configureCollection_args() noexcept;
  CollectionConfig config;

  _Aster_configureCollection_args__isset __isset;

  void __set_config(const CollectionConfig& val);

  bool operator == (const Aster_configureCollection_args & rhs) const;
  bool operator != (const Aster_configureCollection_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_configureCollection_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_configureCollection_pargs {
 public:


  virtual ~Aster_configureCollection_pargs() noexcept;
  const CollectionConfig* config;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_configureCollection_result__isset {
  _Aster_configureCollection_result__isset() : e(false) {}
  bool e :1;
} _Aster_configureCollection_result__isset;

class Aster_configureCollection_result {
 public:

  Aster_configureCollection_result(const Aster_configureCollection_result&);
  Aster_configureCollection_result& operator=(const Aster_configureCollection_result&);
  Aster_configureCollection_result() noexcept;

  virtual ~Aster_configureCollection_result() noexcept;
  AsterError e;

  _Aster_configureCollection_result__isset __isset;

  void __set_e(const AsterError& val);

  bool operator == (const Aster_configureCollection_result & rhs) const;
  bool operator != (const Aster_configureCollection_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_configureCollection_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_configureCollection_presult__isset {
  _Aster_configureCollection_presult__isset() : e(false) {}
  bool e :1;
} _Aster_configureCollection_presult__isset;

class Aster_configureCollection_presult {
 public:


  virtual ~Aster_configureCollection_presult() noexcept;
  AsterError e;

  _Aster_configureCollection_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Aster_dropCollection_args__isset {
  _Aster_dropCollection_args__isset() : name(false) {}
  bool name :1;
} _Aster_dropCollection_args__isset;

class Aster_dropCollection_args {
 public:

  Aster_dropCollection_args(const Aster_dropCollection_args&);
  Aster_dropCollection_args& operator=(const Aster_dropCollection_args&);
  Aster_dropCollection_args() noexcept;

  virtual ~Aster_dropCollection_args() noexcept;
  std::string name;

  _Aster_dropCollection_args__isset __isset;

  void __set_name(const std::string& val);

  bool operator == (const Aster_dropCollection_args & rhs) const;
  bool operator != (const Aster_dropCollection_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_dropCollection_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_dropCollection_pargs {
 public:


  virtual ~Aster_dropCollection_pargs() noexcept;
  const std::string* name;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_dropCollection_result__isset {
  _Aster_dropCollection_result__isset() : e(false) {}
  bool e :1;
} _Aster_dropCollection_result__isset;

class Aster_dropCollection_result {
 public:

  Aster_dropCollection_result(const Aster_dropCollection_result&);
  Aster_dropCollection_result& operator=(const Aster_dropCollection_result&);
  Aster_dropCollection_result() noexcept;

  virtual ~Aster_dropCollection_result() noexcept;
  AsterError e;

  _Aster_dropCollection_result__isset __isset;

  void __set_e(const AsterError& val);

  bool operator == (const Aster_dropCollection_result & rhs) const;
  bool operator != (const Aster_dropCollection_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_dropCollection_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_dropCollection_presult__isset {
  _Aster_dropCollection_presult__isset() : e(false) {}
  bool e :1;
} _Aster_dropCollection_presult__isset;

class Aster_dropCollection_presult {
 public:


  virtual ~Aster_dropCollection_presult() noexcept;
  AsterError e;

  _Aster_dropCollection_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Aster_upsert_args__isset {
  _Aster_upsert_args__isset() : collection(false), doc(false), consistency(false) {}
  bool collection :1;
  bool doc :1;
  bool consistency :1;
} _Aster_upsert_args__isset;

class Aster_upsert_args {
 public:

  Aster_upsert_args(const Aster_upsert_args&);
  Aster_upsert_args& operator=(const Aster_upsert_args&);
  Aster_upsert_args() noexcept;

  virtual ~Aster_upsert_args() noexcept;
  std::string collection;
  Document doc;
  /**
   * 
   * @see ConsistencyLevel
   */
  ConsistencyLevel::type consistency;

  _Aster_upsert_args__isset __isset;

  void __set_collection(const std::string& val);

  void __set_doc(const Document& val);

  void __set_consistency(const ConsistencyLevel::type val);

  bool operator == (const Aster_upsert_args & rhs) const;
  bool operator != (const Aster_upsert_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_upsert_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_upsert_pargs {
 public:


  virtual ~Aster_upsert_pargs() noexcept;
  const std::string* collection;
  const Document* doc;
  /**
   * 
   * @see ConsistencyLevel
   */
  const ConsistencyLevel::type* consistency;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_upsert_result__isset {
  _Aster_upsert_result__isset() : e(false) {}
  bool e :1;
} _Aster_upsert_result__isset;

class Aster_upsert_result {
 public:

  Aster_upsert_result(const Aster_upsert_result&);
  Aster_upsert_result& operator=(const Aster_upsert_result&);
  Aster_upsert_result() noexcept;

  virtual ~Aster_upsert_result() noexcept;
  AsterError e;

  _Aster_upsert_result__isset __isset;

  void __set_e(const AsterError& val);

  bool operator == (const Aster_upsert_result & rhs) const;
  bool operator != (const Aster_upsert_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_upsert_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_upsert_presult__isset {
  _Aster_upsert_presult__isset() : e(false) {}
  bool e :1;
} _Aster_upsert_presult__isset;

class Aster_upsert_presult {
 public:


  virtual ~Aster_upsert_presult() noexcept;
  AsterError e;

  _Aster_upsert_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Aster_get_args__isset {
  _Aster_get_args__isset() : collection(false), id(false), consistency(false) {}
  bool collection :1;
  bool id :1;
  bool consistency :1;
} _Aster_get_args__isset;

class Aster_get_args {
 public:

  Aster_get_args(const Aster_get_args&);
  Aster_get_args& operator=(const Aster_get_args&);
  Aster_get_args() noexcept;

  virtual ~Aster_get_args() noexcept;
  std::string collection;
  std::string id;
  /**
   * 
   * @see ConsistencyLevel
   */
  ConsistencyLevel::type consistency;

  _Aster_get_args__isset __isset;

  void __set_collection(const std::string& val);

  void __set_id(const std::string& val);

  void __set_consistency(const ConsistencyLevel::type val);

  bool operator == (const Aster_get_args & rhs) const;
  bool operator != (const Aster_get_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_get_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_get_pargs {
 public:


  virtual ~Aster_get_pargs() noexcept;
  const std::string* collection;
  const std::string* id;
  /**
   * 
   * @see ConsistencyLevel
   */
  const ConsistencyLevel::type* consistency;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_get_result__isset {
  _Aster_get_result__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _Aster_get_result__isset;

class Aster_get_result {
 public:

  Aster_get_result(const Aster_get_result&);
  Aster_get_result& operator=(const Aster_get_result&);
  Aster_get_result() noexcept;

  virtual ~Aster_get_result() noexcept;
  Document success;
  AsterError e;

  _Aster_get_result__isset __isset;

  void __set_success(const Document& val);

  void __set_e(const AsterError& val);

  bool operator == (const Aster_get_result & rhs) const;
  bool operator != (const Aster_get_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_get_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_get_presult__isset {
  _Aster_get_presult__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _Aster_get_presult__isset;

class Aster_get_presult {
 public:


  virtual ~Aster_get_presult() noexcept;
  Document* success;
  AsterError e;

  _Aster_get_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Aster_remove_args__isset {
  _Aster_remove_args__isset() : collection(false), id(false), consistency(false) {}
  bool collection :1;
  bool id :1;
  bool consistency :1;
} _Aster_remove_args__isset;

class Aster_remove_args {
 public:

  Aster_remove_args(const Aster_remove_args&);
  Aster_remove_args& operator=(const Aster_remove_args&);
  Aster_remove_args() noexcept;

  virtual ~Aster_remove_args() noexcept;
  std::string collection;
  std::string id;
  /**
   * 
   * @see ConsistencyLevel
   */
  ConsistencyLevel::type consistency;

  _Aster_remove_args__isset __isset;

  void __set_collection(const std::string& val);

  void __set_id(const std::string& val);

  void __set_consistency(const ConsistencyLevel::type val);

  bool operator == (const Aster_remove_args & rhs) const;
  bool operator != (const Aster_remove_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_remove_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_remove_pargs {
 public:


  virtual ~Aster_remove_pargs() noexcept;
  const std::string* collection;
  const std::string* id;
  /**
   * 
   * @see ConsistencyLevel
   */
  const ConsistencyLevel::type* consistency;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_remove_result__isset {
  _Aster_remove_result__isset() : e(false) {}
  bool e :1;
} _Aster_remove_result__isset;

class Aster_remove_result {
 public:

  Aster_remove_result(const Aster_remove_result&);
  Aster_remove_result& operator=(const Aster_remove_result&);
  Aster_remove_result() noexcept;

  virtual ~Aster_remove_result() noexcept;
  AsterError e;

  _Aster_remove_result__isset __isset;

  void __set_e(const AsterError& val);

  bool operator == (const Aster_remove_result & rhs) const;
  bool operator != (const Aster_remove_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_remove_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_remove_presult__isset {
  _Aster_remove_presult__isset() : e(false) {}
  bool e :1;
} _Aster_remove_presult__isset;

class Aster_remove_presult {
 public:


  virtual ~Aster_remove_presult() noexcept;
  AsterError e;

  _Aster_remove_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Aster_search_args__isset {
  _Aster_search_args__isset() : req(false) {}
  bool req :1;
} _Aster_search_args__isset;

class Aster_search_args {
 public:

  Aster_search_args(const Aster_search_args&);
  Aster_search_args& operator=(const Aster_search_args&);
  Aster_search_args() noexcept;

  virtual ~Aster_search_args() noexcept;
  SearchRequest req;

  _Aster_search_args__isset __isset;

  void __set_req(const SearchRequest& val);

  bool operator == (const Aster_search_args & rhs) const;
  bool operator != (const Aster_search_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_search_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Aster_search_pargs {
 public:


  virtual ~Aster_search_pargs() noexcept;
  const SearchRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_search_result__isset {
  _Aster_search_result__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _Aster_search_result__isset;

class Aster_search_result {
 public:

  Aster_search_result(const Aster_search_result&);
  Aster_search_result& operator=(const Aster_search_result&);
  Aster_search_result() noexcept;

  virtual ~Aster_search_result() noexcept;
  SearchResponse success;
  AsterError e;

  _Aster_search_result__isset __isset;

  void __set_success(const SearchResponse& val);

  void __set_e(const AsterError& val);

  bool operator == (const Aster_search_result & rhs) const;
  bool operator != (const Aster_search_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aster_search_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Aster_search_presult__isset {
  _Aster_search_presult__isset() : success(false), e(false) {}
  bool success :1;
  bool e :1;
} _Aster_search_presult__isset;

class Aster_search_presult {
 public:


  virtual ~Aster_search_presult() noexcept;
  SearchResponse* success;
  AsterError e;

  _Aster_search_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class AsterClient : virtual public AsterIf {
 public:
  AsterClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  AsterClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void createCollection(const std::string& name) override;
  void send_createCollection(const std::string& name);
  void recv_createCollection();
  void configureCollection(const CollectionConfig& config) override;
  void send_configureCollection(const CollectionConfig& config);
  void recv_configureCollection();
  void dropCollection(const std::string& name) override;
  void send_dropCollection(const std::string& name);
  void recv_dropCollection();
  void upsert(const std::string& collection, const Document& doc, const ConsistencyLevel::type consistency) override;
  void send_upsert(const std::string& collection, const Document& doc, const ConsistencyLevel::type consistency);
  void recv_upsert();
  void get(Document& _return, const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) override;
  void send_get(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency);
  void recv_get(Document& _return);
  void remove(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) override;
  void send_remove(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency);
  void recv_remove();
  void search(SearchResponse& _return, const SearchRequest& req) override;
  void send_search(const SearchRequest& req);
  void recv_search(SearchResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class AsterProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<AsterIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (AsterProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_createCollection(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_configureCollection(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_dropCollection(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_upsert(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_remove(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_search(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  AsterProcessor(::std::shared_ptr<AsterIf> iface) :
    iface_(iface) {
    processMap_["createCollection"] = &AsterProcessor::process_createCollection;
    processMap_["configureCollection"] = &AsterProcessor::process_configureCollection;
    processMap_["dropCollection"] = &AsterProcessor::process_dropCollection;
    processMap_["upsert"] = &AsterProcessor::process_upsert;
    processMap_["get"] = &AsterProcessor::process_get;
    processMap_["remove"] = &AsterProcessor::process_remove;
    processMap_["search"] = &AsterProcessor::process_search;
  }

  virtual ~AsterProcessor() {}
};

class AsterProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  AsterProcessorFactory(const ::std::shared_ptr< AsterIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< AsterIfFactory > handlerFactory_;
};

class AsterMultiface : virtual public AsterIf {
 public:
  AsterMultiface(std::vector<std::shared_ptr<AsterIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~AsterMultiface() {}
 protected:
  std::vector<std::shared_ptr<AsterIf> > ifaces_;
  AsterMultiface() {}
  void add(::std::shared_ptr<AsterIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void createCollection(const std::string& name) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->createCollection(name);
    }
    ifaces_[i]->createCollection(name);
  }

  void configureCollection(const CollectionConfig& config) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->configureCollection(config);
    }
    ifaces_[i]->configureCollection(config);
  }

  void dropCollection(const std::string& name) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->dropCollection(name);
    }
    ifaces_[i]->dropCollection(name);
  }

  void upsert(const std::string& collection, const Document& doc, const ConsistencyLevel::type consistency) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->upsert(collection, doc, consistency);
    }
    ifaces_[i]->upsert(collection, doc, consistency);
  }

  void get(Document& _return, const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get(_return, collection, id, consistency);
    }
    ifaces_[i]->get(_return, collection, id, consistency);
    return;
  }

  void remove(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->remove(collection, id, consistency);
    }
    ifaces_[i]->remove(collection, id, consistency);
  }

  void search(SearchResponse& _return, const SearchRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->search(_return, req);
    }
    ifaces_[i]->search(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class AsterConcurrentClient : virtual public AsterIf {
 public:
  AsterConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  AsterConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void createCollection(const std::string& name) override;
  int32_t send_createCollection(const std::string& name);
  void recv_createCollection(const int32_t seqid);
  void configureCollection(const CollectionConfig& config) override;
  int32_t send_configureCollection(const CollectionConfig& config);
  void recv_configureCollection(const int32_t seqid);
  void dropCollection(const std::string& name) override;
  int32_t send_dropCollection(const std::string& name);
  void recv_dropCollection(const int32_t seqid);
  void upsert(const std::string& collection, const Document& doc, const ConsistencyLevel::type consistency) override;
  int32_t send_upsert(const std::string& collection, const Document& doc, const ConsistencyLevel::type consistency);
  void recv_upsert(const int32_t seqid);
  void get(Document& _return, const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) override;
  int32_t send_get(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency);
  void recv_get(Document& _return, const int32_t seqid);
  void remove(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency) override;
  int32_t send_remove(const std::string& collection, const std::string& id, const ConsistencyLevel::type consistency);
  void recv_remove(const int32_t seqid);
  void search(SearchResponse& _return, const SearchRequest& req) override;
  int32_t send_search(const SearchRequest& req);
  void recv_search(SearchResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
