load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "integration_test",
    size = "small",
    srcs = ["integration_test.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/db",
        "//aster/distributed",
        "//aster/index",
        "//aster/metrics",
        "//aster/platform",
        "//aster/query",
        "//aster/server",
        "//aster/storage",
        "@googletest//:gtest_main",
    ],
)
