load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "aster-bench",
    srcs = ["bench.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/db",
    ],
)

cc_binary(
    name = "multi-tenant-bench",
    srcs = ["multi_tenant_bench.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/server",
    ],
)

cc_binary(
    name = "scale-bench",
    srcs = ["scale_bench.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/db",
        "//aster/distributed",
    ],
)

cc_test(
    name = "bench_test",
    size = "small",
    srcs = ["bench_test.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/db",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "multi_tenant_bench_test",
    size = "small",
    srcs = ["multi_tenant_bench_test.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/server",
        "@googletest//:gtest_main",
    ],
)
