load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "query",
    srcs = ["topk.cc"],
    hdrs = ["topk.h"],
    deps = ["//aster/core"],
)

cc_test(
    name = "query_test",
    size = "small",
    srcs = ["query_test.cc"],
    deps = [
        ":query",
        "@googletest//:gtest_main",
    ],
)
