load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "db",
    srcs = ["db.cc"],
    hdrs = [
        "db.h",
        "storage_mode.h",
    ],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//aster/core",
        "//aster/index",
        "//aster/platform:s3",
        "//aster/query",
        "//aster/storage",
    ],
)

cc_test(
    name = "db_test",
    size = "small",
    srcs = ["db_test.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":db",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "accuracy_profile_test",
    size = "small",
    srcs = ["accuracy_profile_test.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":db",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "storage_mode_test",
    size = "small",
    srcs = ["storage_mode_test.cc"],
    target_compatible_with = select({
        "//platforms:is_baremetal": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":db",
        "//aster/platform:s3",
        "//aster/platform:s3_fake",
        "//aster/server",
        "@googletest//:gtest_main",
    ],
)
